_core:
  default_config_hash: dfTa2HkSKvNWB_DYT7sVaiv7lztYl_vQaZyE9901WpE
social_media:
  facebook_share:
    enable: 1
    text: 'Share in Facebook'
    api_url: 'http://www.facebook.com/share.php?u=[current-page:url]&title=[current-page:title]'
    api_event: href
    default_img: 0
    weight: 1
    attributes: "target|_blank\r\nclass|facebook-share"
    drupalSettings: ''
    img: facebook
    library: ''
  facebook_msg:
    enable: 1
    api_url: 'FB.ui({method: ''send'',link: ''[current-page:url]''})'
    api_event: onclick
    drupalSettings: 'application_id|Your Application ID'
    library: social_media/facebook
    text: 'Facebook messenger'
    default_img: 1
    weight: 2
    attributes: |-
      target|_blank
      class|facebook-msg
      rel|noopener noreferrer
  linkedin:
    enable: 1
    api_url: 'http://www.linkedin.com/shareArticle?mini=true&url=[current-page:url]&title=[current-page:title]&source=[current-page:url]'
    api_event: href
    text: 'Share in Linkedin'
    default_img: 0
    weight: 3
    attributes: "target|_blank\r\nclass|linkedin"
    drupalSettings: ''
    img: linkedin
    library: ''
  twitter:
    enable: 1
    api_url: 'https://twitter.com/intent/tweet?url=[current-page:url]&status=[current-page:title]+[current-page:url]'
    api_event: href
    text: 'Share in Twitter'
    default_img: 0
    weight: 4
    attributes: "target|_blank\r\nclass|twitter"
    drupalSettings: ''
    img: twitter
    library: ''
  pinterest:
    enable: 1
    api_url: 'https://www.pinterest.com/pin/create/button/?url=[current-page:url]&description=[current-page:title]'
    api_event: href
    text: Pinterest
    default_img: 1
    weight: 5
    attributes: |-
      target|_blank
      class|pinterest
      rel|noopener noreferrer
  whatsapp:
    enable: 0
    api_url: 'https://wa.me/?text=[current-page:url]'
    api_event: href
    default_img: 1
    attributes: |-
      class|whatsapp show-for-small-only
      data-action|share/whatsapp/share
    weight: 6
  email:
    enable: 1
    api_url: 'mailto:?subject=[current-page:title]&body=Check out this site [current-page:url]'
    api_event: href
    text: 'Send as an email'
    default_img: 0
    weight: 7
    attributes: class|email
    drupalSettings: ''
    enable_forward: 0
    img: email
    library: ''
    show_forward: 1
  print:
    enable: 0
    api_url: window.print()
    api_event: onclick
    text: Print
    default_img: 1
    attributes: class|print
    weight: 8
langcode: en
